name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Generate
      run: |
        npm i -g hexo
        npm install
        cd ./themes/tranquilpeak/
        npm install
        npm run prod
        cd ../..
        hexo generate
           

