name: CI

on: 
  push:
    paths-ignore:
      - '.github/**'
      - 'source/_drafts/**'
      - 'scaffolds/**'
    branches: 
      - master

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Generate
      run: |
        npm i hexo
        npm install
        cd ./themes/tranquilpeak/
        npm install
        npm run prod
        cd ../..
        npx hexo generate
    - name: Deploy
      env:
         ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
         EXTERNAL_REPOSITORY: laurentkempe/laurentkempe.github.io
         PUBLISH_BRANCH: master
         PUBLISH_DIR: ./public
         INPUT_KEEPFILES: false
         SCRIPT_MODE: true
      run: |
        wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2/entrypoint.sh
        bash ./entrypoint.sh
        
