name: Create new draft

on:
  workflow_dispatch:
    inputs:
      draftTitle:
        description: 'Draft title'
        required: true
        default: 'Draft title'

jobs:
  createDraft:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create draft 📃
      run: |
        npm i hexo
        npm install
        cd ./themes/tranquilpeak/
        npm install
        npm run prod
        cd ../..
        npx hexo new draft '${{ github.event.inputs.draftTitle }}'
    - name: Commit & Push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Add draft ${{ github.event.inputs.draftTitle }}
        commit_user_name: Laurent Kempé
        commit_user_email: ${{ secrets.AUTHOR_EMAIL }}
        file_pattern: source/_drafts/*.md
 
